package:
  name: geoglows
  version: 0.0.1

build:
  noarch: python
  number: 0.0.1

source:
  path: ../

requirements:
  build:
    - python
  run:
    - python>=3
    - pandas
    - plotly>=4
    - requests>=2
    - jinja2>=2.10

about:
  summary: Tools to access and process data from the GEOGloWS initiative
  license: BSD-3-Clause
  license_family: BSD

test:
  imports:
    - requests
    - plotly
    - pandas
    - jinja2
    - geoglows

extra:
  recipe-maintainers:
    - rileyhales