{% set data = load_setup_py_data() %}

package:
  name: geoglows
  version: {{ data['version'] }}

build:
  string: 1
  noarch: python
  preserve_egg_dir: True

source:
  path: ..

requirements:
  build:
    - python
  run:
    - python>=3
    - pandas
    - plotly>=4
    - requests>=2
    - jinja2>=2.10

about:
  home: {{ data['url'] }}
  description: {{ data['description'] }}
  license: {{ data['license'] }}
  license_family: BSD
  doc_url: https://geoglows.readthedocs.io
  dev_url: https://github.com/rileyhales/geoglows

test:
  imports:
    - requests
    - plotly
    - pandas
    - jinja2
    - geoglows

extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - rileyhales