{% set data = load_setup_py_data() %}

package:
  name: geoglows
  version: 0.1.0

about:
  home: https://geoglows.org
  author: Riley Hales
  description: Package for accessing data and APIs developed for the GEOGloWS initiative
  license: BSD 3-Clause License
  license_family: BSD
  doc_url: https://geoglows.readthedocs.io
  dev_url: https://github.com/rileyhales/geoglows

build:
  string: b5
  noarch: python
  preserve_egg_dir: True

source:
  path: ..

requirements:
  build:
    - python
  run:
    - python>=3
    - pandas
    - plotly>=4
    - requests>=2
    - jinja2>=2.10

outputs:
  - name: geoglows

test:
  imports:
    - requests
    - plotly
    - pandas
    - jinja2
    - geoglows

extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - rileyhales