package:
  name: geoglows
  version: 0.0.3

build:
  number: 0.0.3

requirements:
  build:
    - python
  run:
    - python>=3.7
    - pandas>=0.25
    - plotly>=4
    - requests>=2
    - jinja2>=2.10
    - jupyter
    - sphinx
    - sphinx_rtd_theme

about:
  summary: Tools to access and process data from the GEOGloWS initiative
  license: BSD-3-Clause
  license_family: BSD

test:
  imports:
    - requests
    - plotly
    - pandas
    - jinja2

extra:
  recipe-maintainers:
    - rileyhales