package:
  name: geoglows
  version: 0.0.1

build:
  number: 1

requirements:
  build:
    - python
  run:
    - python>=3.7
    - pandas>=0.25
    - plotly>=4
    - requests>=2
    - flask>=1
    - sphinx
    - sphinx_rtd_theme

about:
  summary: This is a package with tools from the GEOGloWS initiative
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

test:
  imports:
    - requests
    - plotly
    - pandas
    - flask

extra:
  recipe-maintainers:
    - rileyhales